### ISSUE TITLE
Decoding error

### ISSUE THREAD

**Issue by CoreSecX** [ipfs/py-ipfs-http-client#171]
Hi,

Do you have any idea, what cause this error?

```
(py37) XXX@bchain:~/projects/ipfs$ python3 ipfstest.py 
<ipfsapi.client.Client object at 0x7f09640be898>
Traceback (most recent call last):
  File "/home/coresec/venv/py37/lib/python3.7/site-packages/ipfsapi/http.py", line 75, in __next__
    data = next(self._response_iter)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ipfstest.py", line 14, in <module>
    api.add('2nd')
  File "/home/coresec/venv/py37/lib/python3.7/site-packages/ipfsapi/client.py", line 189, in add
    data=body, headers=headers, **kwargs)
  File "/home/coresec/venv/py37/lib/python3.7/site-packages/ipfsapi/http.py", line 38, in wrapper
    return func(self, *args, **merged)
  File "/home/coresec/venv/py37/lib/python3.7/site-packages/ipfsapi/http.py", line 245, in request
    files, headers, data)
  File "/home/coresec/venv/py37/lib/python3.7/site-packages/ipfsapi/http.py", line 191, in _request
    ret = stream_decode_full(res, parser)
  File "/home/coresec/venv/py37/lib/python3.7/site-packages/ipfsapi/http.py", line 115, in stream_decode_full
    result = list(response_iter)
  File "/home/coresec/venv/py37/lib/python3.7/site-packages/ipfsapi/http.py", line 83, in __next__
    self._parser_iter   = iter(self._parser.parse_finalize())
  File "/home/coresec/venv/py37/lib/python3.7/site-packages/ipfsapi/encoding.py", line 254, in parse_finalize
    raise exceptions.DecodingError('json', self._lasterror)
ipfsapi.exceptions.DecodingError: Object decoding error: Expecting value: line 1 column 1 (char 0)

XXX@bchain:~/projects/ipfs$ pip3 show ipfsapi
Name: ipfsapi
Version: 0.4.3

XXX@bchain:~/projects/ipfs$ python3 --version
Python 3.7.0

XXX@bchain:~/projects/ipfs$ uname -a
Linux bchain 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
```

The code:

```
import ipfsapi
import io

if __name__ == '__main__':
  try:
      api = ipfsapi.connect('127.0.0.1', 8080)
      print(api)
  except ipfsapi.exceptions.connectionerror as IACE:
      print(str(IACE))

with io.open('2nd','w',encoding='utf-8') as newFile:
    newFile.write('Follow the white rabbit')

```
If I use the api.add('2nd') code, the result is the same.

**Comment by alexander255** [comment]
Port 8080 is the port of the gateway, no? The error message basically says that the library expected the reply to be JSON, but it wasn't. You probably want to use `ipfsapi.connect('127.0.0.1', 5001)` instead to connect to the IPFS API service instead.

**Comment by CoreSecX** [comment]
Thanks, will have another look.
